### PR TITLE
Add 1aim

### PR DESCRIPTION
**Pull request by Hoverbear**
Adds 1aim as a gold sponsor.

Note: We might consider adjusting our sponsor image sizes a bit. This one shows up visibly more prominent than some others.

### CODE REVIEW

**Comment by apiraino** [comment]
> Note: We might consider adjusting our sponsor image sizes a bit. This one shows up visibly more prominent than some others.

indeed. unfortunately my css mad skillz do not allow me to help here :-/

**Review by apiraino — APPROVED** [review]

**Comment by badboy** [comment]
I'll check that

**Comment by badboy** [comment]
So I separated them into the groups and made them smaller depending on their level:

sponsor levels

1aim still sticks out a bit.

**Comment by badboy** [comment]
I attached the changes as displayed above.
cc @apiraino

**Comment by Hoverbear** [comment]
LGTM

**Comment by apiraino** [comment]
> I attached the changes as displayed above.
> cc @apiraino

very nice, thanks!

**Pull request merged**
