### PR TITLE
About page updates

### PR DESCRIPTION
**Pull request by apiraino**
* Added a priority parameter to sort members
* Shrunk images down
* Fixed favicon

### CODE REVIEW

**Comment by apiraino** [comment]
Pls help me fix the members sorting ;-)

**Comment by badboy** [comment]
Old: 11.74 MB transferred
New: 1.09 MB transferred

**Comment by badboy** [comment]
Addresses #5

**Review by badboy — APPROVED** [review]

**Comment by badboy** [comment]
Let's defer sorting to a follow-up

**Pull request merged**
